buffered_tile: W:/2025_CA_Eastern_Municipal_WD_LUCD_097667.00/2_Models/block_4/output_buffered/EMWD_lc_344.tif
target_size: W:/2025_CA_Eastern_Municipal_WD_LUCD_097667.00/2_Models/block_4/output_buffered/EMWD_lc_343.tif
