img_dir: C:/Users/nathan.kossnar/Pictures/CCAP_codes.png
label_dir: W:/2025_CA_Eastern_Municipal_WD_LUCD_097667.00/2_Models/!Model_Testing/block_4/unet_v2_aug_resnet101_lr-05_d0005_b16_adam_ce_rgn_epoch10_0.181_0.931_predictions
